.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lightcoin_qt test_lightcoin_qt
clean: FORCE
	$(MAKE) -C .. lightcoin_qt_clean test_lightcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_lightcoin_qt_check
lightcoin-qt lightcoin-qt.exe: FORCE
	 $(MAKE) -C .. lightcoin_qt
